### ISSUE TITLE
Poor performance on some maps

### ISSUE THREAD

**Issue by ntorring** [mustachedk/android-beacon-bacon-lib#1]
The map does not become visible for "Hovedbiblioteket" on a OnePlus One running Android 6. On a Samsung galaxy s8 the map struggles with low framerate for 1. floor on "Hovedbiblioteket".
The issue seems to be with the generated bitmaps being to large, on the OnePlus i get the following message:
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3800x5022, max=4096x4096)

**Comment by ghost** [comment]
We are working on resolving the issue with bitmaps being too large to be uploaded into a texture.

**Comment by ghost** [comment]
Issue has been resolved with ver 1.0.6 of the library
