### ISSUE TITLE
Crash on hardware back button push, while map is loading

### ISSUE THREAD

**Issue by RasmusFredensborg** [mustachedk/android-beacon-bacon-lib#7]
When pressing hardware back button, just before map is loaded, the following nullpointer exception is thrown:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap dk.mustache.beaconbacon.datamodels.BBRequestObject.getImage()' on a null object reference
                      at dk.mustache.beaconbacon.customviews.CustomSnackbar.make(CustomSnackbar.java:62)
                      at dk.mustache.beaconbacon.activities.BeaconBaconActivity.showFindTheBookSnackbar(BeaconBaconActivity.java:447)

**Comment by ghost** [comment]
I am unable to reproduce this issue. Are you using the latest version?
`implementation 'com.github.mustachedk:android-beacon-bacon-lib:1.0.21'`

Also, please ensure you are supplying the BBRequestObject with a Bitmap of the image - in this case a book icon, decoded from the resources:
```
BeaconBaconManager.getInstance().setRequestObject(new BBRequestObject("IMS", faustId, "En mand der hedder Ove", "SK", BitmapFactory.decodeResource(getResources(), R.drawable.ic_book)));
Intent intentWayfinding = new Intent(DemoActivity.this, BeaconBaconActivity.class);
intentWayfinding.putExtra(PLACE_ID, placeId);
intentWayfinding.putExtra(FAUST_ID, faustId);
startActivity(intentWayfinding);
overridePendingTransition(R.anim.slide_in_bottom, R.anim.hold_anim);
```

**Comment by RasmusFredensborg** [comment]
Hi @DeadCounter 
Yes, I'm using version 1.0.21. The problem is not that a Bitmap is not supplied - it's a timing issue. If the AsyncTask is executed and the user presses back in between the task is processed and the task is finished, the BBRequestObject will be null and the crash will occur.

It's difficult to reproduce, as you have to hit the back button at just the right time, so it's not a crucial issue - but it exists :-)

**Comment by ghost** [comment]
Okay, I see. Apparently I didn't fix all the issues that caused the back-button crash.

I'll implement a proper handling of this one as well, and let you know when I push an update. :)

**Comment by ghost** [comment]
@RasmusFredensborg - I pushed an update that should take care of the issue (though I am still not able to reproduce it), let me know if its still causing trouble! :)

**Comment by kledk** [comment]
It is still an issue. We can reproduce the issue when we start the intent and press the hardware back button at the right time, it will happen.
