### ISSUE TITLE
No back/close button on Android

### ISSUE THREAD

**Issue by kledk** [mustachedk/android-beacon-bacon-lib#8]
We are expericening no back/close button when we, putExtra(PLACE_ID, placeId); on the intent, ie. when we are navigating to wayfinding without a faustId.

**Comment by ghost** [comment]
I cannot reproduce this issue. Can you elaborate what device model + version you are running? Also, can you paste the code for the intent, so I can try to reproduce the issue? In the DemoActivity I am running with the library, I open this Intent just fine:

                Intent intentNoWayfinding = new Intent(DemoActivity.this, BeaconBaconActivity.class);
                intentNoWayfinding.putExtra(PLACE_ID, placeId);
                startActivity(intentNoWayfinding);
                overridePendingTransition(R.anim.slide_in_bottom, R.anim.hold_anim);

Please ensure you are not adding unnecessary flags to the Intent.

**Comment by kledk** [comment]
The problem is not that the intent is not opening, but that there is no back/close button in the top-right  corner, on the new wayfinding screen, so that the user can go back to our app.

Running on a pixel 2 simulator, android 8.0.


![screenshot_1534759068](https://user-images.githubusercontent.com/3142986/44333863-4e321e80-a470-11e8-9bc9-8c4cff067d6a.png)

This is our code

```
Intent intentWayfinding = new Intent(this.context, BeaconBaconActivity.class);
        if(placeId != null && !placeId.isEmpty()) {
            intentWayfinding.putExtra(PLACE_ID, placeId);
        }

        if(faustId != null && !faustId.isEmpty()) {
            intentWayfinding.putExtra(FAUST_ID, faustId);
        }
        this.context.startActivity(intentWayfinding);
```

**Comment by ghost** [comment]
Ah! Now I see. Okay, so the user can actually go back using the built in back-button that all Android devices have on the bottom left side, either as a physical button on the device, or as a software key. I'll implement a 'close' button in the top right corner as well, just as the iOS app has.

I'll let you know when I push an update. :)

**Comment by ghost** [comment]
@kledk - Okay, I'm not really sure what's happening here, I can see from your latest build that the issue is present, but when I build using our DemoActivity, I do not have the issue. The issue must be on your end. I have a hard time seeing what the issue could be though.
